#!/bin/bash

export SLICE_UNIT="--slice zebrakow.slice"
export REMOTE_HOST=""
export CONTAINER=""
export RUN=""
export SYSTEMD_RUN_MACHINE=""
export TERMINAL=""

export RUN_CONTAINER_REMOTE=""

function machine() {
    if [[ $REMOTE_HOST == "" ]]; then
	MACHINE="$CONTAINER"
	export RUN="machinectl --quiet $MACHINE shell /bin/bash -c "
	export SYSTEMD_RUN_MACHINE="$CONTAINER"
    elif [[ $CONTAINER == "" ]]; then
	MACHINE="$(echo $REMOTE_HOST | cut -f1 -d:)"
	export SYSTEMD_RUN_MACHINE="-H $REMOTE_HOST"
	export RUN="ssh $MACHINE"
	REMOTE_CONTAINER="$(echo $REMOTE_HOST | cut -f2- -d:)"
	if [[ $REMOTE_CONTAINER -ne "" ]]; then
	    export RUN_CONTAINER_REMOTE="machinectl --quiet -M $REMOTE_CONTAINER shell /bin/bash -c "
	fi
    fi
}

function metadata() {

    if [[ -e /etc/machine-info ]]; then
	source /etc/machine-info;
    fi
    echo "JOB_ID=$1"
    echo "CMDLINE=$(cat /proc/$(systemctl status $UNIT | grep Main\ PID: | sed s/\ Main\ PID:\ //g | awk '{print $1}')/comm)"
    echo "TIME=Running `systemctl status $UNIT | grep Active | sed s/\ \ \ Active:\ active\ \(running\)\ //g`"
    echo "UNIT=$UNIT"
    echo "SLICE=$(systemctl show -p Slice $UNIT | sed s/Slice=//g )"
    echo "STATUS=$(systemctl status $UNIT | grep Status: | sed s/\ \ \ Status:\ //g)"
    echo "PID=$(systemctl status $UNIT | grep Main\ PID: | sed s/\ Main\ PID:\ //g | awk '{print $1}')"
    echo "--"
    echo "MEMORY=$(systemctl status $UNIT | grep Memory: | awk '{print $2}')"
    echo "TASKS=$(systemctl status $UNIT | grep Tasks: | sed s/\ \ \ \ Tasks:\ //g)"
    echo "CPU=$(systemctl status $UNIT | grep CPU: | awk '{print $2}')"
    echo "CGROUP=$(systemctl status $UNIT | grep CGroup: | awk '{print $2}')"
    echo "IP=$(systemctl status $UNIT | grep IP: | sed s/\ \ \ \ \ \ \ IP:\ //g)"
    echo "LOG_TARGET=$(systemctl show -p StandardOutput $UNIT | sed s/StandardOutput=//g)"
    echo "--"
    echo "MACHINE_HOSTNAME=$(hostname)"
    echo "MACHINE_ID=$(cat /etc/machine-id)"
    echo "MACHINE_PRETTY_HOSTNAME=$(echo $PRETTY_HOSTNAME)"
    echo "MACHINE_LOCATION=$(echo $LOCATION)"
}

function usage() {
    printf "Usage: %s [OPTIONS] {COMMAND}\n" $0
    printf "\nOptions:\n"
    printf "\t-H USER@HOST:container Operate on remote host\n"
    printf "\t-M epsilon  \tOperate on local container\n"
    printf "\t-l\t\tList running jobs\n"
    printf "\t-t\t\tAttach to the terminal\n"
    printf "\t-h\t\tDisplay this help\n"
    printf "\t-S foobar.slice Run under this slice unit\n"
    printf "\t-j {job} OPT\tOperate on the job\n"
    printf "\n\tSuboptions for -j:\n"
    printf "\t-u\tView logs for the job\n"
    printf "\t-f\tFollow the build log of a running job\n"
    printf "\t-m\tDisplay metadata of a running job\n"
    printf "\t-s\tDisplay status of a running job's unit\n"
    printf "\t-i\tInspect the unit file of a running job\n"
    printf "\t-k\tKill the job\n"
    exit 0
}

while getopts "H:M:lthj:S:" opt; do
    case $opt in
	H)
	    if [[ $CONTAINER -ne "" ]]; then
		echo "Only one of -H -or -M may be specified at once" >&2
		exit 1
	    fi
	    export REMOTE_HOST="$OPTARG"
	    machine
	    ;;
	M)
	    if [[ $REMOTE_HOST -ne "" ]]; then
		echo "Only one of -H -or -M may be specified at once" >&2
		exit 1
	    fi
	    export CONTAINER="-M $OPTARG"
	    machine
	    ;;
	l)
	    $RUN $RUN_CONTAINER_REMOTE "if [[ ! -e /run/zebrakow ]]; then echo '/run/zebrakow not found!' >&2 && exit 1; fi"
	    $RUN $RUN_CONTAINER_REMOTE tree /run/zebrakow | head -n-1
	    NUM=$($RUN ls -l /run/zebrakow | grep ^d | wc -l)
	    echo
	    echo "$NUM job(s) listed"
	    RUNNING=$($RUN $RUN_CONATINER_REMOTE tree /run/zeebrakow | grep RUNNING | wc -l)
	    COMPLETED=$($RUN $RUN_CONTAINER_REMOTE tree /run/zeebrakow | grep COMPLETED | wc -l)
	    FAILED=$($RUN $RUN_CONTAINER_REMOTE tree /run/zeebrakow | grep FAILED | wc -l)
	    echo "└── $RUNNING job(s) running"
	    echo "└── $COMPLETED job(s) completed"
	    echo "└── $FAILED job(s) failed"
	    exit 0
	    ;;
	t)
	    TERMINAL="--pty"
	    ;;
	h)
	    usage
	    ;;
	j)
    	    JOB_ID=$OPTARG
	    $RUN $RUN_CONTAINER_REMOTE "if [[ ! -e /run/zebrakow/$OPTARG ]]; then echo 'No jobs with this JOB_ID!' >&2; exit 1; fi"
	    echo
	    UNIT=$($RUN $RUN_CONTAINER_REMOTE readlink /run/zebrakow/$JOB_ID/UNIT)
	    echo "Unit $UNIT has JOB_ID $JOB_ID"
	    echo
	    shift $((OPTIND-1))
	    case $1 in
		-u)
		    journalctl $SYSTEMD_RUN_MACHINE -u $UNIT && exit $?
		    ;;
		-f) 
		    journalctl $SYSTEMD_RUN_MACHINE -u $UNIT && exit $?
		    ;;
		-m)
		    $RUN metadata $JOB_ID
		    exit 0
		    ;;
		-s)
		    systemctl $SYSTEMD_RUN_MACHINE status $UNIT && exit $?
		    ;;
		-i)
		    systemctl $SYSTEMD_RUN_MACHINE cat $UNIT && exit $?
		    ;;
		-k)
		    systemctl $SYSTEMD_RUN_MACHINE kill $UNIT && exit $?
		    ;;
		*)
		    echo "Unknown argument. Also, only a single argument may be passed." >&2
		    exit 1
		    ;;
	    esac
	    ;;
	S)
	    SLICE_UNIT="--slice $OPTARG"
	    ;;
	    
	:)
	    echo "Missing option argument for -$OPTARG" >&2;
	    exit 1
	    ;;
        *)
	    echo "Unknown option: -$OPTARG" >&2;
	    exit 1
	    ;;
    esac
done

shift $((OPTIND-1))
systemd-run $SYSTEMD_RUN_MACHINE $SLICE_UNIT $TERMINAL\
	    -p Type=notify -p NotifyAccess=all \
	    -p ExecStartPre=/usr/lib/zebrakow/zebrakow-setup\ --start\ '$INVOCATION_ID' \
	    -p Environment=HOME=/root \
	    -p ExecStopPost=/usr/lib/zebrakow/zebrakow-setup\ --stop\ '$INVOCATION_ID' \
	    $@
